name: max30101
description: Package which integrates with the max30101 sensor, producing illustrative heart rate and O2 saturation readings
version: 1.0.0-RC3
repository: https://github.com/atsign-foundation/max30101

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  dart_periphery: ^0.8.25-RC
